Adjust SPI code to handle negative/zero Stokes components.
ratt-ru/codex-africanus pull request #276
Opened 2023-04-06 13:57 UTC by JSKenyon

- [x] Tests added / passed

  ```bash
  $ py.test -v -s africanus
  ```

  If the pep8 tests fail, the quickest way to correct
  this is to run `autopep8` and then `flake8` and
  `pycodestyle` to fix the remaining issues.

  ```
  $ pip install -U autopep8 flake8 pycodestyle
  $ autopep8 -r -i africanus
  $ flake8 africanus
  $ pycodestyle africanus
  ```

- [x] Fully documented, including `HISTORY.rst` for all changes
      and one of the `docs/*-api.rst` files for new API

  To build the docs locally:

  ```
  pip install -r requirements.readthedocs.txt
  cd docs
  READTHEDOCS=True make html
  ```

2023-04-06 14:42 UTC, sjperkins requested changes
Thanks for putting this fix in. Could you change the following test case to use the `log` base?

https://github.com/ratt-ru/codex-africanus/blob/7a756a9bd3fe8bfadb2a02add9b3f180be42696d/africanus/experimental/rime/fused/tests/test_rime.py#L250-L253

There are other cases that use the standard base and it would be nice to cover this case too.



https://github.com/ratt-ru/codex-africanus/blob/master/africanus/experimental/rime/fused/tests/test_rime.py

2023-04-11 08:54 UTC, JSKenyon commented
I have made the requested changes and propagated the fixes to the other SPI evaluation code.

2023-04-11 09:54 UTC, sjperkins requested changes
This looks good. Can you add the following entry to HISTORY.rst? "Adjust SPI code to handle negative/zero Stokes components".

I suggest prefixing the commit with "[skip ci]" to avoid kicking off the CI build. i.e. something like "[skip ci] Update HISTORY.rst".

2023-04-11 12:12 UTC, sjperkins approved these changes

2023-04-11 12:12 UTC, merged